services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frotend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    